/**
 * Generates a one-shot install script with agent binding credentials.
 * The generic binary is downloaded once; per-host secrets go into /etc/vortex-agent.env.
 */

export type AgentInstallParams = {
  agentId: string
  secret: string
  /** ws(s)://host — AgentWSURL appends /ws/agent */
  coreUrl: string
  /** Base URL that hosts vortex-agent-linux-amd64 etc. Optional. */
  binaryBaseUrl?: string
}

function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** Derive agent Core base URL for outbound WSS. */
export function resolveAgentCoreUrl(): string {
  const explicit = import.meta.env.VITE_AGENT_CORE_URL?.trim()
  if (explicit) return explicit.replace(/\/$/, '')

  const ws = import.meta.env.VITE_WS_URL?.trim()
  if (ws) {
    try {
      const u = new URL(ws)
      // strip trailing /ws used by browser clients
      u.pathname = u.pathname.replace(/\/ws\/?$/, '') || ''
      u.search = ''
      u.hash = ''
      const path = u.pathname.replace(/\/$/, '')
      return `${u.protocol}//${u.host}${path === '/' ? '' : path}`
    } catch {
      /* fall through */
    }
  }

  // Vite dev proxies /ws → :8000; agents must hit Core directly.
  if (import.meta.env.DEV) {
    const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    return `${proto}//127.0.0.1:8000`
  }

  const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
  return `${proto}//${window.location.host}`
}

export function resolveAgentBinaryBaseUrl(): string | undefined {
  const v = import.meta.env.VITE_AGENT_BINARY_BASE_URL?.trim()
  return v ? v.replace(/\/$/, '') : undefined
}

/** Full bash script ready to run as root on the target host. */
export function buildAgentInstallScript(params: AgentInstallParams): string {
  const core = shSingleQuote(params.coreUrl)
  const id = shSingleQuote(params.agentId)
  const secret = shSingleQuote(params.secret)
  const binaryBase = params.binaryBaseUrl
    ? shSingleQuote(params.binaryBaseUrl)
    : "''"

  return `#!/usr/bin/env bash
# Vortex Agent enroll — generated by Vortex Web (one-time secret inside).
set -euo pipefail

if [[ "\${EUID}" -ne 0 ]]; then
  echo "re-run as root: curl ... | sudo bash" >&2
  exit 1
fi

VORTEX_CORE_URL=${core}
VORTEX_AGENT_ID=${id}
VORTEX_SECRET_TOKEN=${secret}
VORTEX_AGENT_BINARY_BASE_URL=${binaryBase}
BIN_PATH=/usr/local/bin/vortex-agent
ENV_PATH=/etc/vortex-agent.env
UNIT_PATH=/etc/systemd/system/vortex-agent.service

detect_asset() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "\${arch}" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) echo "unsupported arch: \${arch}" >&2; exit 1 ;;
  esac
  case "\${os}" in
    linux) echo "vortex-agent-linux-\${arch}" ;;
    darwin) echo "vortex-agent-darwin-\${arch}" ;;
    *) echo "unsupported os: \${os}" >&2; exit 1 ;;
  esac
}

if [[ -n "\${VORTEX_AGENT_BINARY_BASE_URL}" ]]; then
  asset="$(detect_asset)"
  url="\${VORTEX_AGENT_BINARY_BASE_URL}/\${asset}"
  tmp="$(mktemp)"
  echo "downloading \${url}"
  curl -fsSL "\${url}" -o "\${tmp}"
  install -Dm755 "\${tmp}" "\${BIN_PATH}"
  rm -f "\${tmp}"
elif [[ ! -x "\${BIN_PATH}" ]]; then
  echo "No VITE_AGENT_BINARY_BASE_URL configured and \${BIN_PATH} missing." >&2
  echo "Build once: (cd VortexAgent && make cross) and host the artifacts," >&2
  echo "or copy vortex-agent to \${BIN_PATH}." >&2
  exit 1
fi

umask 077
cat >"\${ENV_PATH}" <<EOF
VORTEX_CORE_URL=\${VORTEX_CORE_URL}
VORTEX_AGENT_ID=\${VORTEX_AGENT_ID}
VORTEX_SECRET_TOKEN=\${VORTEX_SECRET_TOKEN}
VORTEX_LOG_LEVEL=info
EOF
chmod 600 "\${ENV_PATH}"

cat >"\${UNIT_PATH}" <<'UNIT'
[Unit]
Description=Vortex Agent — outbound tunnel to Vortex Core
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-/etc/vortex-agent.env
ExecStart=/usr/local/bin/vortex-agent
Restart=always
RestartSec=2
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
UNIT

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload
  systemctl enable --now vortex-agent
  systemctl --no-pager --full status vortex-agent || true
else
  nohup "\${BIN_PATH}" >/var/log/vortex-agent.log 2>&1 &
fi

echo "Vortex Agent online enroll OK (agent_id=\${VORTEX_AGENT_ID})"
`
}

/**
 * Paste-on-server one-liner: decode + sudo bash (no hosted URL required).
 * Secret is inside the payload — treat like a password.
 */
export function buildAgentInstallOneLiner(params: AgentInstallParams): string {
  const script = buildAgentInstallScript(params)
  // browser btoa needs binary string; script is ASCII
  const b64 = btoa(unescape(encodeURIComponent(script)))
  return `echo '${b64}' | base64 -d | sudo bash`
}

export function buildAgentInstallBundle(params: Omit<AgentInstallParams, 'coreUrl' | 'binaryBaseUrl'> & {
  coreUrl?: string
  binaryBaseUrl?: string
}) {
  const full: AgentInstallParams = {
    agentId: params.agentId,
    secret: params.secret,
    coreUrl: params.coreUrl ?? resolveAgentCoreUrl(),
    binaryBaseUrl: params.binaryBaseUrl ?? resolveAgentBinaryBaseUrl(),
  }
  const script = buildAgentInstallScript(full)
  const oneLiner = buildAgentInstallOneLiner(full)
  return { ...full, script, oneLiner }
}
