/**
 * Generates a one-shot install script with agent binding credentials.
 * The generic binary is downloaded from Vortex Web `/agent/`;
 * per-host secrets go into /etc/vortex-agent.env only.
 */

export type AgentInstallParams = {
  agentId: string
  secret: string
  /** ws(s)://host — AgentWSURL appends /ws/agent */
  coreUrl: string
  /** Absolute base URL that hosts vortex-agent-linux-amd64 etc. */
  binaryBaseUrl: string
}

function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** Derive agent Core base URL for outbound WSS. */
export function resolveAgentCoreUrl(): string {
  const explicit = import.meta.env.VITE_AGENT_CORE_URL?.trim()
  if (explicit) return explicit.replace(/\/$/, '')

  const ws = import.meta.env.VITE_WS_URL?.trim()
  if (ws) {
    try {
      const u = new URL(ws)
      u.pathname = u.pathname.replace(/\/ws\/?$/, '') || ''
      u.search = ''
      u.hash = ''
      const path = u.pathname.replace(/\/$/, '')
      return `${u.protocol}//${u.host}${path === '/' ? '' : path}`
    } catch {
      /* fall through */
    }
  }

  // Vite dev proxies /ws → :8000; agents must hit Core directly.
  if (import.meta.env.DEV) {
    return 'ws://127.0.0.1:8000'
  }

  const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
  return `${proto}//${window.location.host}`
}

/**
 * Where enroll scripts download the shared agent binary from.
 * Defaults to current Vortex Web origin + /agent (auto — no manual env required).
 */
export function resolveAgentBinaryBaseUrl(): string {
  const v = import.meta.env.VITE_AGENT_BINARY_BASE_URL?.trim()
  if (v) return v.replace(/\/$/, '')

  if (typeof window !== 'undefined' && window.location?.origin) {
    return `${window.location.origin}/agent`
  }

  // Last resort (should not happen in browser); keep absolute-ish path for debug.
  return '/agent'
}

function requireBinaryBaseUrl(raw?: string): string {
  const base = (raw?.trim() || resolveAgentBinaryBaseUrl()).replace(/\/$/, '')
  if (!base || base === '/') {
    throw new Error('Agent binary base URL is empty — open Vortex Web over http(s) and retry Install agent')
  }
  // Remote hosts cannot resolve relative /agent — require absolute URL in the script.
  if (base.startsWith('/')) {
    if (typeof window !== 'undefined' && window.location?.origin) {
      return `${window.location.origin}${base}`
    }
    throw new Error('Agent binary URL must be absolute (https://web-host/agent)')
  }
  return base
}

/** Full bash script ready to run as root on the target host. */
export function buildAgentInstallScript(params: AgentInstallParams): string {
  const core = shSingleQuote(params.coreUrl)
  const id = shSingleQuote(params.agentId)
  const secret = shSingleQuote(params.secret)
  const binaryBase = shSingleQuote(requireBinaryBaseUrl(params.binaryBaseUrl))

  return `#!/usr/bin/env bash
# Vortex Agent enroll — generated by Vortex Web (one-time secret inside).
set -euo pipefail

if [[ "\${EUID}" -ne 0 ]]; then
  echo "re-run as root: curl ... | sudo bash" >&2
  exit 1
fi

VORTEX_CORE_URL=${core}
VORTEX_AGENT_ID=${id}
VORTEX_SECRET_TOKEN=${secret}
VORTEX_AGENT_BINARY_BASE_URL=${binaryBase}
BIN_PATH=/usr/local/bin/vortex-agent
ENV_PATH=/etc/vortex-agent.env
UNIT_PATH=/etc/systemd/system/vortex-agent.service

detect_asset() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "\${arch}" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) echo "unsupported arch: \${arch}" >&2; exit 1 ;;
  esac
  case "\${os}" in
    linux) echo "vortex-agent-linux-\${arch}" ;;
    darwin) echo "vortex-agent-darwin-\${arch}" ;;
    *) echo "unsupported os: \${os}" >&2; exit 1 ;;
  esac
}

install_binary() {
  local asset url tmp code
  asset="$(detect_asset)"
  url="\${VORTEX_AGENT_BINARY_BASE_URL%/}/\${asset}"
  tmp="$(mktemp)"
  echo "downloading \${url}"
  code="$(curl -fsSL -w '%{http_code}' "\${url}" -o "\${tmp}" || true)"
  if [[ "\${code}" != "200" ]]; then
    rm -f "\${tmp}"
    echo "ERROR: download failed (HTTP \${code}) from \${url}" >&2
    echo "Vortex Web must serve agent binaries at /agent/ (rebuild Web image with agent stage)." >&2
    exit 1
  fi
  if head -c 16 "\${tmp}" | grep -qi '<!DOCTYPE\\|<html\\|text/html'; then
    rm -f "\${tmp}"
    echo "ERROR: \${url} returned HTML, not a binary (SPA fallback or missing file)." >&2
    exit 1
  fi
  install -Dm755 "\${tmp}" "\${BIN_PATH}"
  rm -f "\${tmp}"
  echo "installed \${BIN_PATH}"
}

install_binary

umask 077
cat >"\${ENV_PATH}" <<EOF
VORTEX_CORE_URL=\${VORTEX_CORE_URL}
VORTEX_AGENT_ID=\${VORTEX_AGENT_ID}
VORTEX_SECRET_TOKEN=\${VORTEX_SECRET_TOKEN}
VORTEX_LOG_LEVEL=info
EOF
chmod 600 "\${ENV_PATH}"

cat >"\${UNIT_PATH}" <<'UNIT'
[Unit]
Description=Vortex Agent — outbound tunnel to Vortex Core
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-/etc/vortex-agent.env
ExecStart=/usr/local/bin/vortex-agent
Restart=always
RestartSec=2
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
UNIT

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload
  systemctl enable --now vortex-agent
  systemctl --no-pager --full status vortex-agent || true
else
  nohup "\${BIN_PATH}" >/var/log/vortex-agent.log 2>&1 &
fi

echo "Vortex Agent online enroll OK (agent_id=\${VORTEX_AGENT_ID})"
`
}

/**
 * Paste-on-server one-liner: decode + sudo bash (no hosted URL required for the script itself).
 * Secret is inside the payload — treat like a password.
 */
export function buildAgentInstallOneLiner(params: AgentInstallParams): string {
  const script = buildAgentInstallScript(params)
  const b64 = btoa(unescape(encodeURIComponent(script)))
  return `echo '${b64}' | base64 -d | sudo bash`
}

export function buildAgentInstallBundle(params: Omit<AgentInstallParams, 'coreUrl' | 'binaryBaseUrl'> & {
  coreUrl?: string
  binaryBaseUrl?: string
}) {
  const full: AgentInstallParams = {
    agentId: params.agentId,
    secret: params.secret,
    coreUrl: params.coreUrl ?? resolveAgentCoreUrl(),
    binaryBaseUrl: requireBinaryBaseUrl(params.binaryBaseUrl),
  }
  const script = buildAgentInstallScript(full)
  const oneLiner = buildAgentInstallOneLiner(full)
  return { ...full, script, oneLiner }
}
